[package]
name = "stellar-archivist"
description = "Stellar History Archive tools and utilities."
homepage = "https://github.com/stellar/rs-stellar-archivist"
repository = "https://github.com/stellar/rs-stellar-archivist"
authors = ["Stellar Development Foundation <info@stellar.org>"]
license = "Apache-2.0"
version = "0.1.0"
edition = "2021"
rust-version = "1.74.0"

[lib]
name = "stellar_archivist"

[[bin]]
name = "stellar-archivist"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0.139", features = ["derive"] }
serde_json = { version = "1.0.89" }
clap = { version = "4.0", features = ["derive"] }
tokio = { version = "1.35", features = ["rt-multi-thread", "macros", "fs", "io-util", "sync", "time"] }
anyhow = { version = "1.0" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "ansi"] }
futures-util = { version = "0.3" }
url = { version = "2.5" }
async-trait = "0.1"
reqwest = { version = "0.12", default-features = false, features = [
    "rustls-tls",        # TLS backend (force rustls, no native-tls)
    "http2",             # Enable HTTP/2 support
    "stream",            # Streaming responses
] }
tokio-util = { version = "0.7.16", features = ["compat", "io"] }
lru = { version = "0.12" }

[dev-dependencies]
tempfile = { version = "3.5.0" }
rand = { version = "0.8" }
rstest = { version = "0.18.2" }
tokio-test = { version = "0.4" }
axum = { version = "0.7" }
tower = { version = "0.5" }
tower-http = { version = "0.6", features = ["fs"] }
walkdir = { version = "2" }
wiremock = { version = "0.6" }